// <auto-generated />
namespace Hinet.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alter_tbls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_tbls));
        
        string IMigrationMetadata.Id
        {
            get { return "202510131710425_alter_tbls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
